name: Bohemian Bicycles
favicon: null
layout_spectrum: 0.34264
typography_spectrum: 0.06373165990225971
title: 'Bohemian Bicycles '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3125
  lightness: 0.7458315270487219
  saturation: 0.5785467685200274
  rhythmicContrast: 0.3143446655012667
purpose: []
